[build]
builder = "nixpacks"
installCommand = "npm install"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthCheckPath = "/api/ping"
healthCheckTimeout = 100
restartPolicy = "always"
# Trigger redeploy: 2026-04-22 18:50
